### PR TITLE
Get the verbose switch out of subcommands

### PR DESCRIPTION
**Pull request by jecaro**
This fix the issue #39

### CODE REVIEW

**Comment by apauley** [comment]
Great stuff, @jecaro! Much appreciated. This is setting the stage for further tasks related to the command-line interface redesign (#14).

You mentioned that #38 was your first PR, congratulations!
But similarly, for this project you are the first contributor other than myself :-)

I'll probably have to make contributions official in some way, and since this project is in the hledger ecosystem I'm thinking of using the hledger Contributor Agreement:
https://hledger.org/contributors.html

Please comment if you have any opinions on the matter.

**Comment by jecaro** [comment]
As you wish @apauley , I have no opinion on this.

**Comment by apauley** [comment]
Thanks @jecaro, I've added a contributor's agreement and would be honored if you would add yourself as the first external contributor:

https://github.com/apauley/hledger-flow/blob/master/CONTRIBUTING.org#list-of-contributors

**Comment by jecaro** [comment]
Ok. I'll do it :-)

**Pull request merged**
